/*
 * This is the main file. Here, all the routers, errors etc. are setup
*/
var createError = require('http-errors');
var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');

var indexRouter = require('./routes/index');

/* These routers tell the backend to go to the given file to handle the request*/
var providersRouter = require('./routes/providersList');
var classesRouter = require('./routes/courseList')

/*
 Autogenerated code
*/

var app = express();

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

/*
 Here, we're connecting the files with the route. So the router is used when there is a request to the given route
*/
app.use('/', indexRouter);
app.use('/providers-list', providersRouter);
app.use('/course-list', classesRouter)


/*
 Autogenerated code
*/

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;